### PR TITLE
Fixes issue #52

### PR DESCRIPTION
**Pull request by mwilli20**
Sorry about the last branch, I forgot I made the in github edit, and couldn't figure out what was wrong.
In response to the Php strings, they have a new string type in Php 5.

<<<EOD
Example of string
spanning multiple lines
using heredoc syntax.
EOD;

<<< Starts the comment, and then gets a variable name, and doesn't end until that variable name comes up again.

### CODE REVIEW

**Comment by Aaronepower** [comment]
@mwilli20 I think tokei should implement those style of comments, however that is out of scope for this issue. It MR looks fine, however can you either post here, or amend the commit message to say what exactly has been done? Just so the commit history is nicer, and I can use it later when I want to update the changelog.

**Comment by mwilli20** [comment]
Modification on comments:
	Batch  - Add ::
	Lisp   - Comments can be nested (www.rosettacode.org/wiki/Comments#Common_Lisp)
	Python - Reverted to hash, based on comment thread from pull #59 as
		string has a return value

Changes to the quotes
	Assembly     -  Uses ' ' or " "
	Bash              - Uses ' ' or " "
	Batch             -  They don't use quotes for strings
	Cold Fusion - Uses ' ' or " "
	D                      - Uses " " or ` `
	Dart                - Uses " " or ' ' or """  """ or ''' '''
	Forth             - Uses " " but new, doesn't have a preset
	Fortrans       - Use " " or ' '
	Idris                - Uses " " or """ """
	Julia               - Uses " " or """ """
	Kotlin             - Uses " " or """ """
	Moustache  - Uses " " or ' '
	Nim                 - Uses " " or """ """
	Pascal           - Uses ' '
	Perl                 - Uses " " or ' '
	Php                 - Uses " " or ' '
	Python          - Uses " " or ' ' or """  """ or ''' '''
	Ruby              - Uses " " or ' '
	Sass               - Uses " " or ' '
	Sql                   - Uses ' '
	Toml               - Uses " " or ' ' or """ """ or ''' '''
	Typescript   - Uses " " or ' ' or ` `
	Vimscript     - Uses " " or ' '
	Yaml               - Uses " " or ' '
	Zsh                 - Uses " " or ' '

**Comment by mwilli20** [comment]
@Aaronepower Do you want to make an issue for Php or should I make one?

**Comment by Aaronepower** [comment]
@mwilli20 I'll do it you've done enough. :smile:

**Comment by mwilli20** [comment]
@Aaronepower Hope it helps

**Pull request merged**
