### PR TITLE
Add support for .el, .ede, .org and .srt files

### PR DESCRIPTION
**Pull request by kaushalmodi**
Add support for following file extensions:

- Emacs Lisp (.el)
- Emacs Development Environement (.ede)
- Org mode (.org)
- SRecode (.srt)

### CODE REVIEW

**Comment by Aaronepower** [comment]
Thanks for your PR and congrats on your first contribution! Could you also add some test files for the extensions in `tests/data` there are plenty of examples there and if you need any help with them just ask in this PR.

**Comment by kaushalmodi** [comment]
I can add the tests, but what command should I run to verify that the test passed locally? I am not a Rust coder, so please let me know the commands I need to type in the terminal.

Thanks!

**Comment by Aaronepower** [comment]
@kaushalmodi All you need to run is `cargo test` 😄

**Comment by kaushalmodi** [comment]
> All you need to test is to run cargo test

That was easy. Though, a related question.. do I need to `cargo clean` to run the test after adding each new test? Seems like so...

I was just adding one test at a time, testing it and then adding another one.

**Comment by kaushalmodi** [comment]
@Aaronepower I have added tests; please review.

**Comment by kaushalmodi** [comment]
@Aaronepower Bump. Also do you know why the build is failing?

**Comment by Aaronepower** [comment]
Thank you fro your PR!

**Pull request merged**
