### PR TITLE
Add GraphQL support

### PR DESCRIPTION
**Pull request by stefanmaric**

### CODE REVIEW

**Comment by Aaronepower** [comment]
@stefanmaric Thank you for your PR! It seems the count in the test file is slightly off or is there an inaccuracy in tokei?

**Comment by stefanmaric** [comment]
Hi!

It is probably my dyslexia. I didn't have the proper setup to run the tests
so I counted on the CI. I'll check again later tonight.

This PR is a mess, I will probably squash it. :D

Best,

**Comment by Aaronepower** [comment]
@stefanmaric I always squash PRs when I merge them, so don't worry about doing that.

**Comment by stefanmaric** [comment]
That was a big round of dummy mistakes, but looks good now. Gotta install `rustup` for the next time, I'm sorry to choke the CI servers. :smile:

**Comment by Aaronepower** [comment]
Thank you again for your work, and congrats on your first contribution! :tada:

**Pull request merged**
