### PR TITLE
Add Ur/Web support

### PR DESCRIPTION
**Pull request by tuncer**

### CODE REVIEW

**Comment by Aaronepower** [comment]
Can you give some sort of reference data to this language?

**Comment by tuncer** [comment]
Do you mean test files or more info?

http://www.impredicative.com/ur/

https://air.mozilla.org/ur-web-a-simple-model-for-programming-the-web/

**Comment by Aaronepower** [comment]
A single test file would be enough, thank you.

**Comment by tuncer** [comment]
Done.

**Pull request merged**
