### PR TITLE
Avoid panicking on non-character-boundary inside string slice

### LINKED ISSUE #55: `--files` flag may cause panic when file path has non-ASCII characters
For example:

> tokei --files D:\tmp\新建文件夹\tokei

```
-------------------------------------------------------------------------------
 Language            Files        Lines         Code     Comments       Blanks
-------------------------------------------------------------------------------
...
-------------------------------------------------------------------------------
thread 'main' panicked at 'index 17 and/or 41 in `D:\tmp\新建文件夹\tokei\CHANGELOG.md` do not lie on character boundary', ../src/libcore\str/mod.rs:1721
stack backtrace:
   0:   0xd98f9b - std::rt::lang_start::haaae1186de9de8cb
   1:   0xd9989a - std::panicking::rust_panic_with_hook::hb1322e5f2588b4db
   2:   0xd99736 - std::panicking::begin_panic_fmt::h4fe9fb9d5109c4bf
   3:   0xd995eb - rust_begin_unwind
   4:   0xda05f7 - core::panicking::panic_fmt::h4395919ece15c671
   5:   0xda12c0 - core::str::slice_error_fail::h9ad582f282290cd6
   6:   0xd0c602 - <tokei::stats::Stats as core::fmt::Display>::fmt::h4eaabf7e66bef4ca
   7:   0xcf5bae - __ImageBase
   8:   0xda25af - core::fmt::write::h300d6e605e327781
```

### PR DESCRIPTION
**Pull request by liigo**
Fixes #55

### CODE REVIEW

**Comment by liigo** [comment]
I'm nearly sure that these failing tests is not my fault. And I don't know how to do with that.

**Comment by Aaronepower** [comment]
@liigo Yeah, don't worry about those tests. I'm going to make a commit to fix that regression later, and then I'll merge this in.

**Comment by Aaronepower** [comment]
@liigo Can you rebase this commit on top of the latest master?

**Comment by liigo** [comment]
@Aaronepower  Done.

**Pull request merged**
