### PR TITLE
bump ignore to 0.3, rayon to 0.9, handlebars to 0.29, hex to 0.3

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
@Aaronepower anything to do here from my side?

**Comment by Aaronepower** [comment]
@ignatenkobrain No, just the CI acting up, we'll see how this rebuild goes and if it fails I'm going to just merge it in regardless.

**Comment by ignatenkobrain** [comment]
@Aaronepower I think CI was failing just on rust nightly...

**Comment by Aaronepower** [comment]
@ignatenkobrain It wasn't nightly, nightly is allowed to fail. It was problems with the cache.

**Comment by Aaronepower** [comment]
Thank you for this PR!

**Pull request merged**
