### PR TITLE
Add Emojicode

### PR DESCRIPTION
**Pull request by MagnificentPako**

### CODE REVIEW

**Comment by Aaronepower** [comment]
Hello! Congrats on your first contribution to Tokei!

Could you also add some test code under `tests/data/emojicode.emojic` It just needs to be code that contains all types of comments and strings and those comments in strings. There are plenty of good examples in that folder([especially rust.rs](https://github.com/Aaronepower/tokei/blob/master/tests/data/rust.rs)) and if you have any trouble just ask here and I'll help you.

**Comment by MagnificentPako** [comment]
Anything I can do to fix the broken CI tests?

**Comment by Aaronepower** [comment]
@MagnificentPako No, I'll fix those :) I just pushed a commit that changed language.json formatting could you change yours to match it?

**Comment by Aaronepower** [comment]
Closing due to inactivity. Feel free to resubmit the PR with those formatting changes and I'll merge it in!

**Pull request closed without merging**
