### PR TITLE
Move CI to trust

### PR DESCRIPTION
**Pull request by alexeyzab**
These changes configure the trust template to use the correct
credentials and project name.

This is an initial pass at setting up the new CI. If there are any
addition tweaks that need to be done here, let me know.

Thanks!

#120

### CODE REVIEW

**Comment by Aaronepower** [comment]
Thank you for the PR! The nightly channels seem to be consistently failing to build. Could you have a look at why?

**Comment by alexeyzab** [comment]
@Aaronepower Sure! It seems to be a recent issue with rustup: https://github.com/rust-lang-nursery/rustup.rs/issues/1092. I'll keep checking till it gets resolved.

**Comment by alexeyzab** [comment]
I enabled `allow_failures` for nightly builds on travis-ci. I keep trying to get the same option to work for appveyor, but I think I am messing up the config file somehow. Sorry about that.

**Comment by Aaronepower** [comment]
This looks great! Could you also add a beta channel, so we can know ahead of time if tokei has a soundness bug or anything similar before it hits stable.

**Comment by alexeyzab** [comment]
Done. Let me know if there is anything else I can help with here.

**Comment by Aaronepower** [comment]
@alexeyzab Sorry, we want betas to give us an error on failure. I'm also not seeing any beta builds in either travis or appveyor?

**Comment by alexeyzab** [comment]
@Aaronepower My bad, I'll look into that.

**Comment by alexeyzab** [comment]
I've added beta channels back in for both travis and appveyor. I took all the targets from the old .travis.yml.

**Comment by Aaronepower** [comment]
Thank you!

**Pull request merged**
