### PR TITLE
Add F* support

### PR DESCRIPTION
**Pull request by tuncer**

### CODE REVIEW

**Comment by tuncer** [comment]
I based this on the definition for OCaml, and it seems to share the same fault of not identifying comments. I'm not sure where the definitions for `"base":"func"` are inherited from.

**Comment by tuncer** [comment]
Configuring comment syntax in `"multi":[]` and removing `"base":"func"` doesn't make a difference.

**Comment by Aaronepower** [comment]
Thanks for the PR. Actually having base does make a difference as it allows tokei to re use the FUNC_REGEX, over creating a new REGEX. If you could switch it back to `"base": "func"`, I'd be happy to merge it in.

**Comment by tuncer** [comment]
> If you could switch it back to "base": "func", I'd be happy to merge it in.

Done.

**Comment by tuncer** [comment]
So why are comments not listed in the results for OCaml, Coq, F*, etc?

**Comment by tuncer** [comment]
> Actually having base does make a difference

Code reuse is why I had it in the first version, but since the explicit multi comment definition is the same as in base:func, there's no point. It made no difference in the sense that comments are still uncounted.

Why are comments not listed in the results for OCaml, Coq, F*, etc?

**Comment by Aaronepower** [comment]
I'm not sure what you mean, can you provide a sample code base where the comments aren't being counted?

**Comment by tuncer** [comment]
Let's discuss it in #89.

**Comment by Aaronepower** [comment]
I'm going to add merge this now, as this seems like the correct implementation, the problem with FUNC_REGEX is a seperate issue.

**Pull request merged**
