### PR TITLE
add support for Meson

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Fixes: https://github.com/Aaronepower/tokei/issues/168
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
I tried to add test for it, but it fails...

```meson
# 12 lines 6 code 2 comments 4 blanks

project('xyz', 'c',
        meson_version : '>=0.30.0') # not counted

xyz_gen = '''
# comment inside
print("This is generated source.")
'''

# this is a comment

```

It treats `# comment inside` as a real comment while it is in multiline quote, so it seems to be bug in tokei.

**Comment by Aaronepower** [comment]
@ignatenkobrain Can you add the test back in? So it can be added with the PR and I can test it.

**Comment by ignatenkobrain** [comment]
@Aaronepower done.

**Comment by Aaronepower** [comment]
@ignatenkobrain Can you rebase this onto the new master and see if the test continues to fail?

**Comment by ignatenkobrain** [comment]
@Aaronepower 

```
---- meson stdout ----
	Meson LINES MATCH
thread 'meson' panicked at 'assertion failed: `(left == right)`
  left: `6`,
 right: `4`', /home/brain/Projects/upstream/tokei/target/debug/build/tokei-623c5e7e142d4c32/out/tests.rs:744:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by Aaronepower** [comment]
@ignatenkobrain I've looked into the error and I think the problem is that you've set `'''` as a multi line comment when it is a string literal and should be in `quotes`, switching it to that makes it work.

**Comment by ignatenkobrain** [comment]
@Aaronepower so I pushed new version, but it still fails because of lines of code, it thinks that it is 5, but I think that it is 6.

**Comment by Aaronepower** [comment]
@ignatenkobrain Okay, the latest commit should fix that inaccuracy.

**Comment by ignatenkobrain** [comment]
@Aaronepower thanks! should be ready for merge

**Comment by Aaronepower** [comment]
@ignatenkobrain Thank you for the PR!

**Pull request merged**
